# Site settings
title: "FrontierHacks19: Humanoid" 
email: ctianyich@gmail.com
description:
baseurl: "https://ctychen.github.io/FrontierHacks19" 
url: "https://ctychen.github.io/FrontierHacks19" # the base hostname & protocol for your site

twitter_username:
github_username: ctychen

# Build settings
markdown: kramdown
